[versions]
minecraft = "26.1-snapshot-7"

# Fabric
fabric-api = "0.143.4+26.1"
fabric-loom = "1.15-SNAPSHOT"
fabric-loader = "0.18.4"

# NeoForge
neoforge-main = "26.1.0.0-alpha.11+snapshot-7"
neoforge-loader = "4"
neoforge-moddev = "2.0.140"

# Other dependencies
asm = "9.9.1"
mixin = "0.8.3"
devauth = "1.2.2"
slf4j = "2.0.17"
lombok = "1.18.42"
junit = "5.10.0"

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
devauth-fabric = { group = "me.djtheredstoner", name = "DevAuth-fabric", version.ref = "devauth" }
devauth-neoforge = { group = "me.djtheredstoner", name = "DevAuth-neoforge", version.ref = "devauth" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }