modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/azurejelly/reconnect/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/azurejelly/reconnect"
logoFile="icon.png"
authors="azurejelly"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"